In [10]:
import os
import numpy as np
import pandas as pd

In [11]:
dir_data = './data/'

In [17]:
f_app = os.path.join(dir_data, 'HomeCredit_columns_description.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/HomeCredit_columns_description.csv

In [19]:
app_train.head(10)

,Unnamed: 0,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
6,9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
7,10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
8,11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
9,12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN

In [20]:
app_train.tail(5)

,Unnamed: 0,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
200,217,installments_payments.csv,NUM_INSTALMENT_NUMBER,On which installment we observe payment,NaN,NaN,NaN
201,218,installments_payments.csv,DAYS_INSTALMENT,When the installment of previous credit was su...,time only relative to the application,NaN,NaN
202,219,installments_payments.csv,DAYS_ENTRY_PAYMENT,When was the installments of previous credit p...,time only relative to the application,NaN,NaN
203,220,installments_payments.csv,AMT_INSTALMENT,What was the prescribed installment amount of ...,NaN,NaN,NaN
204,221,installments_payments.csv,AMT_PAYMENT,What the client actually paid on previous cred...,NaN,NaN,NaN

In [23]:
app_train[5:]

,Unnamed: 0,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
6,9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
7,10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
8,11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
9,12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN
10,13,application_{train|test}.csv,AMT_GOODS_PRICE,For consumer loans it is the price of the good...,NaN,NaN,NaN
11,14,application_{train|test}.csv,NAME_TYPE_SUITE,Who was accompanying client when he was applyi...,NaN,NaN,NaN
12,15,application_{train|test}.csv,NAME_INCOME_TYPE,"Clients income type (businessman, working, mat...",NaN,NaN,NaN
13,16,application_{train|test}.csv,NAME_EDUCATION_TYPE,Level of highest education the client achieved,NaN,NaN,NaN
14,17,application_{train|test}.csv,NAME_FAMILY_STATUS,Family status of the client,NaN,NaN,NaN
15,18,application_{train|test}.csv,NAME_HOUSING_TYPE,What is the housing situation of the client (r...,NaN,NaN,NaN
16,19,application_{train|test}.csv,REGION_POPULATION_RELATIVE,Normalized population of region where client l...,normalized,NaN,NaN
17,20,application_{train|test}.csv,DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application,NaN,NaN
18,21,application_{train|test}.csv,DAYS_EMPLOYED,How many days before the application the perso...,time only relative to the application,NaN,NaN
19,22,application_{train|test}.csv,DAYS_REGISTRATION,How many days before the application did clien...,time only relative to the application,NaN,NaN
20,23,application_{train|test}.csv,DAYS_ID_PUBLISH,How many days before the application did clien...,time only relative to the application,NaN,NaN
21,24,application_{train|test}.csv,OWN_CAR_AGE,Age of client's car,NaN,NaN,NaN
22,25,application_{train|test}.csv,FLAG_MOBIL,"Did client provide mobile phone (1=YES, 0=NO)",NaN,NaN,NaN
23,26,application_{train|test}.csv,FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)",NaN,NaN,NaN
24,27,application_{train|test}.csv,FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN,NaN,NaN
25,28,application_{train|test}.csv,FLAG_CONT_MOBILE,"Was mobile phone reachable (1=YES, 0=NO)",NaN,NaN,NaN
26,29,application_{train|test}.csv,FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN,NaN,NaN
27,30,application_{train|test}.csv,FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)",NaN,NaN,NaN
28,31,application_{train|test}.csv,OCCUPATION_TYPE,What kind of occupation does the client have,NaN,NaN,NaN
29,32,application_{train|test}.csv,CNT_FAM_MEMBERS,How many family members does client have,NaN,NaN,NaN
30,33,application_{train|test}.csv,REGION_RATING_CLIENT,Our rating of the region where client lives (1...,NaN,NaN,NaN
31,34,application_{train|test}.csv,REGION_RATING_CLIENT_W_CITY,Our rating of the region where client lives wi...,NaN,NaN,NaN
32,35,application_{train|test}.csv,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...,NaN,NaN,NaN
33,36,application_{train|test}.csv,HOUR_APPR_PROCESS_START,Approximately at what hour did the client appl...,rounded,NaN,NaN
34,37,application_{train|test}.csv,REG_REGION_NOT_LIVE_REGION,Flag if client's permanent address does not ma...,NaN,NaN,NaN
...,...,...,...,...,...,...,...
175,178,previous_application.csv,NAME_CONTRACT_TYPE,"Contract product type (Cash loan, consumer loa...",NaN,NaN,NaN
176,179,previous_application.csv,AMT_ANNUITY,Annuity of previous application,NaN,NaN,NaN
177,180,previous_application.csv,AMT_APPLICATION,For how much credit did client ask on the prev...,NaN,NaN,NaN
178,181,previous_application.csv,AMT_CREDIT,Final credit amount on the previous applicatio...,NaN,NaN,NaN
179,182,previous_application.csv,AMT_DOWN_PAYMENT,Down payment on the previous application,NaN,NaN,NaN
180,183,previous_application.csv,AMT_GOODS_PRICE,Goods price of good that client asked for (if ...,NaN,NaN,NaN
181,184,previous_application.csv,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...,NaN,NaN,NaN
182,185,previous_application.csv,HOUR_APPR_PROCESS_START,Approximately at what day hour did the client ...,rounded,NaN,NaN
183,186,previous_application.csv,FLAG_LAST_APPL_PER_CONTRACT,Flag if it was last application for the previo...,NaN,NaN,NaN
184,187,previous_application.csv,NFLAG_LAST_APPL_IN_DAY,Flag if the application was the last applicati...,NaN,NaN,NaN
185,188,previous_application.csv,NFLAG_MICRO_CASH,Flag Micro finance loan,NaN,NaN,NaN
186,189,previous_application.csv,RATE_DOWN_PAYMENT,Down payment rate normalized on previous credit,normalized,NaN,NaN
187,190,previous_application.csv,RATE_INTEREST_PRIMARY,Interest rate normalized on previous credit,normalized,NaN,NaN
188,191,previous_application.csv,RATE_INTEREST_PRIVILEGED,Interest rate normalized on previous credit,normalized,NaN,NaN
189,192,previous_application.csv,NAME_CASH_LOAN_PURPOSE,Purpose of the cash loan,NaN,NaN,NaN
190,193,previous_application.csv,NAME_CONTRACT_STATUS,"Contract status (approved, cancelled, ...) of ...",NaN,NaN,NaN
191,194,previous_application.csv,DAYS_DECISION,Relative to current application when was the d...,time only relative to the application,NaN,NaN
192,195,previous_application.csv,NAME_PAYMENT_TYPE,Payment method that client chose to pay for th...,NaN,NaN,NaN
193,196,previous_application.csv,CODE_REJECT_REASON,Why was the previous application rejected,NaN,NaN,NaN
194,197,previous_application.csv,NAME_TYPE_SUITE,Who accompanied client when applying for the p...,NaN,NaN,NaN
195,198,previous_application.csv,NAME_CLIENT_TYPE,Was the client old or new client when applying...,NaN,NaN,NaN
196,199,previous_application.csv,NAME_GOODS_CATEGORY,What kind of goods did the client apply for in...,NaN,NaN,NaN
197,200,previous_application.csv,NAME_PORTFOLIO,"Was the previous application for CASH, POS, CA...",1,"2 or more previous loans in Home Credit)""",hashed
198,215,installments_payments.csv,SK_ID_CURR,ID of loan in our sample,hashed,NaN,NaN
199,216,installments_payments.csv,NUM_INSTALMENT_VERSION,Version of installment calendar (0 is for cred...,NaN,NaN,NaN
200,217,installments_payments.csv,NUM_INSTALMENT_NUMBER,On which installment we observe payment,NaN,NaN,NaN
201,218,installments_payments.csv,DAYS_INSTALMENT,When the installment of previous credit was su...,time only relative to the application,NaN,NaN
202,219,installments_payments.csv,DAYS_ENTRY_PAYMENT,When was the installments of previous credit p...,time only relative to the application,NaN,NaN
203,220,installments_payments.csv,AMT_INSTALMENT,What was the prescribed installment amount of ...,NaN,NaN,NaN
204,221,installments_payments.csv,AMT_PAYMENT,What the client actually paid on previous cred...,NaN,NaN,NaN

In [24]:
app_train.Row

0                       SK_ID_CURR
1                           TARGET
2               NAME_CONTRACT_TYPE
3                      CODE_GENDER
4                     FLAG_OWN_CAR
5                  FLAG_OWN_REALTY
6                     CNT_CHILDREN
7                 AMT_INCOME_TOTAL
8                       AMT_CREDIT
9                      AMT_ANNUITY
10                 AMT_GOODS_PRICE
11                 NAME_TYPE_SUITE
12                NAME_INCOME_TYPE
13             NAME_EDUCATION_TYPE
14              NAME_FAMILY_STATUS
15               NAME_HOUSING_TYPE
16      REGION_POPULATION_RELATIVE
17                      DAYS_BIRTH
18                   DAYS_EMPLOYED
19               DAYS_REGISTRATION
20                 DAYS_ID_PUBLISH
21                     OWN_CAR_AGE
22                      FLAG_MOBIL
23                  FLAG_EMP_PHONE
24                 FLAG_WORK_PHONE
25                FLAG_CONT_MOBILE
26                      FLAG_PHONE
27                      FLAG_EMAIL
28                 OCCUPATION_TYPE
29                 CNT_FAM_MEMBERS
                  ...
175             NAME_CONTRACT_TYPE
176                    AMT_ANNUITY
177                AMT_APPLICATION
178                     AMT_CREDIT
179               AMT_DOWN_PAYMENT
180                AMT_GOODS_PRICE
181     WEEKDAY_APPR_PROCESS_START
182        HOUR_APPR_PROCESS_START
183    FLAG_LAST_APPL_PER_CONTRACT
184         NFLAG_LAST_APPL_IN_DAY
185               NFLAG_MICRO_CASH
186              RATE_DOWN_PAYMENT
187          RATE_INTEREST_PRIMARY
188       RATE_INTEREST_PRIVILEGED
189         NAME_CASH_LOAN_PURPOSE
190           NAME_CONTRACT_STATUS
191                  DAYS_DECISION
192              NAME_PAYMENT_TYPE
193             CODE_REJECT_REASON
194                NAME_TYPE_SUITE
195               NAME_CLIENT_TYPE
196            NAME_GOODS_CATEGORY
197                 NAME_PORTFOLIO
198                     SK_ID_CURR
199         NUM_INSTALMENT_VERSION
200          NUM_INSTALMENT_NUMBER
201                DAYS_INSTALMENT
202             DAYS_ENTRY_PAYMENT
203                 AMT_INSTALMENT
204                    AMT_PAYMENT
Name: Row, Length: 205, dtype: object

In [28]:
bond=pd.read_csv(f_app, index_col="Unnamed: 0")

In [29]:
bond.head(10)

,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN

In [30]:
bond.index

Int64Index([  1,   2,   5,   6,   7,   8,   9,  10,  11,  12,
            ...
            198, 199, 200, 215, 216, 217, 218, 219, 220, 221],
           dtype='int64', length=205)

In [31]:
bond.set_index("Table", inplace=True)

In [32]:
bond.head(10)

,Row,Description,Special,Unnamed: 5,Unnamed: 6
Table,,,,,
application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN

In [33]:
bond.index

Index(['application_{train|test}.csv', 'application_{train|test}.csv',
       'application_{train|test}.csv', 'application_{train|test}.csv',
       'application_{train|test}.csv', 'application_{train|test}.csv',
       'application_{train|test}.csv', 'application_{train|test}.csv',
       'application_{train|test}.csv', 'application_{train|test}.csv',
       ...
       'previous_application.csv', 'previous_application.csv',
       'previous_application.csv', 'installments_payments.csv',
       'installments_payments.csv', 'installments_payments.csv',
       'installments_payments.csv', 'installments_payments.csv',
       'installments_payments.csv', 'installments_payments.csv'],
      dtype='object', name='Table', length=205)

In [36]:
bond

,Row,Description,Special,Unnamed: 5,Unnamed: 6
Table,,,,,
application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN
application_{train|test}.csv,AMT_GOODS_PRICE,For consumer loans it is the price of the good...,NaN,NaN,NaN
application_{train|test}.csv,NAME_TYPE_SUITE,Who was accompanying client when he was applyi...,NaN,NaN,NaN
application_{train|test}.csv,NAME_INCOME_TYPE,"Clients income type (businessman, working, mat...",NaN,NaN,NaN
application_{train|test}.csv,NAME_EDUCATION_TYPE,Level of highest education the client achieved,NaN,NaN,NaN
application_{train|test}.csv,NAME_FAMILY_STATUS,Family status of the client,NaN,NaN,NaN
application_{train|test}.csv,NAME_HOUSING_TYPE,What is the housing situation of the client (r...,NaN,NaN,NaN
application_{train|test}.csv,REGION_POPULATION_RELATIVE,Normalized population of region where client l...,normalized,NaN,NaN
application_{train|test}.csv,DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application,NaN,NaN
application_{train|test}.csv,DAYS_EMPLOYED,How many days before the application the perso...,time only relative to the application,NaN,NaN
application_{train|test}.csv,DAYS_REGISTRATION,How many days before the application did clien...,time only relative to the application,NaN,NaN
application_{train|test}.csv,DAYS_ID_PUBLISH,How many days before the application did clien...,time only relative to the application,NaN,NaN
application_{train|test}.csv,OWN_CAR_AGE,Age of client's car,NaN,NaN,NaN
application_{train|test}.csv,FLAG_MOBIL,"Did client provide mobile phone (1=YES, 0=NO)",NaN,NaN,NaN
application_{train|test}.csv,FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)",NaN,NaN,NaN
application_{train|test}.csv,FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN,NaN,NaN
application_{train|test}.csv,FLAG_CONT_MOBILE,"Was mobile phone reachable (1=YES, 0=NO)",NaN,NaN,NaN
application_{train|test}.csv,FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN,NaN,NaN
application_{train|test}.csv,FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)",NaN,NaN,NaN
application_{train|test}.csv,OCCUPATION_TYPE,What kind of occupation does the client have,NaN,NaN,NaN
application_{train|test}.csv,CNT_FAM_MEMBERS,How many family members does client have,NaN,NaN,NaN
...,...,...,...,...,...
previous_application.csv,NAME_CONTRACT_TYPE,"Contract product type (Cash loan, consumer loa...",NaN,NaN,NaN
previous_application.csv,AMT_ANNUITY,Annuity of previous application,NaN,NaN,NaN
previous_application.csv,AMT_APPLICATION,For how much credit did client ask on the prev...,NaN,NaN,NaN
previous_application.csv,AMT_CREDIT,Final credit amount on the previous applicatio...,NaN,NaN,NaN
previous_application.csv,AMT_DOWN_PAYMENT,Down payment on the previous application,NaN,NaN,NaN
previous_application.csv,AMT_GOODS_PRICE,Goods price of good that client asked for (if ...,NaN,NaN,NaN
previous_application.csv,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...,NaN,NaN,NaN
previous_application.csv,HOUR_APPR_PROCESS_START,Approximately at what day hour did the client ...,rounded,NaN,NaN
previous_application.csv,FLAG_LAST_APPL_PER_CONTRACT,Flag if it was last application for the previo...,NaN,NaN,NaN
previous_application.csv,NFLAG_LAST_APPL_IN_DAY,Flag if the application was the last applicati...,NaN,NaN,NaN
previous_application.csv,NFLAG_MICRO_CASH,Flag Micro finance loan,NaN,NaN,NaN
previous_application.csv,RATE_DOWN_PAYMENT,Down payment rate normalized on previous credit,normalized,NaN,NaN
previous_application.csv,RATE_INTEREST_PRIMARY,Interest rate normalized on previous credit,normalized,NaN,NaN
previous_application.csv,RATE_INTEREST_PRIVILEGED,Interest rate normalized on previous credit,normalized,NaN,NaN
previous_application.csv,NAME_CASH_LOAN_PURPOSE,Purpose of the cash loan,NaN,NaN,NaN
previous_application.csv,NAME_CONTRACT_STATUS,"Contract status (approved, cancelled, ...) of ...",NaN,NaN,NaN
previous_application.csv,DAYS_DECISION,Relative to current application when was the d...,time only relative to the application,NaN,NaN
previous_application.csv,NAME_PAYMENT_TYPE,Payment method that client chose to pay for th...,NaN,NaN,NaN
previous_application.csv,CODE_REJECT_REASON,Why was the previous application rejected,NaN,NaN,NaN
previous_application.csv,NAME_TYPE_SUITE,Who accompanied client when applying for the p...,NaN,NaN,NaN
previous_application.csv,NAME_CLIENT_TYPE,Was the client old or new client when applying...,NaN,NaN,NaN
previous_application.csv,NAME_GOODS_CATEGORY,What kind of goods did the client apply for in...,NaN,NaN,NaN
previous_application.csv,NAME_PORTFOLIO,"Was the previous application for CASH, POS, CA...",1,"2 or more previous loans in Home Credit)""",hashed
installments_payments.csv,SK_ID_CURR,ID of loan in our sample,hashed,NaN,NaN
installments_payments.csv,NUM_INSTALMENT_VERSION,Version of installment calendar (0 is for cred...,NaN,NaN,NaN
installments_payments.csv,NUM_INSTALMENT_NUMBER,On which installment we observe payment,NaN,NaN,NaN
installments_payments.csv,DAYS_INSTALMENT,When the installment of previous credit was su...,time only relative to the application,NaN,NaN
installments_payments.csv,DAYS_ENTRY_PAYMENT,When was the installments of previous credit p...,time only relative to the application,NaN,NaN
installments_payments.csv,AMT_INSTALMENT,What was the prescribed installment amount of ...,NaN,NaN,NaN
installments_payments.csv,AMT_PAYMENT,What the client actually paid on previous cred...,NaN,NaN,NaN

In [41]:
app_train.set_index("Unnamed: 0", inplace=True)

In [43]:
app_train.head(10)

,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
Unnamed: 0,,,,,,
1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN

In [44]:
app_train.reset_index(inplace=True)

In [45]:
app_train.head(10)

,Unnamed: 0,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
6,9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
7,10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
8,11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
9,12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN

In [46]:
app_train.set_index("Unnamed: 0", inplace=True)

In [47]:
app_train.loc[10]

Table          application_{train|test}.csv
Row                        AMT_INCOME_TOTAL
Description            Income of the client
Special                                 NaN
Unnamed: 5                              NaN
Unnamed: 6                              NaN
Name: 10, dtype: object

In [52]:
app_train.loc[[1, 2]]

,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
Unnamed: 0,,,,,,
1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN

In [53]:
app_train_1=pd.read_csv(f_app)

In [54]:
app_train_1.iloc[15]

Unnamed: 0                                                    18
Table                               application_{train|test}.csv
Row                                            NAME_HOUSING_TYPE
Description    What is the housing situation of the client (r...
Special                                                      NaN
Unnamed: 5                                                   NaN
Unnamed: 6                                                   NaN
Name: 15, dtype: object

In [55]:
app_train_1.iloc[1:5]

,Unnamed: 0,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN

In [57]:
app_train_1.loc[1:5]

,Unnamed: 0,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN

In [58]:
app_train_1.loc[3, "Table"]

'application_{train|test}.csv'

In [59]:
app_train_1.rename(columns={"Unnamed: 0":"Index"}, inplace=True)

In [60]:
app_train_1.head(10)

,Index,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
6,9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
7,10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
8,11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
9,12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN

In [61]:
app_train_1.rename(index={2:3}, inplace=True)

In [65]:
app_train_1[:5]

,Index,Table,Row,Description,Special,Unnamed: 5,Unnamed: 6
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
3,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN,NaN,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN

In [67]:
app_train_1.drop(labels=["Table"], axis="columns")

,Index,Row,Description,Special,Unnamed: 5,Unnamed: 6
0,1,SK_ID_CURR,ID of loan in our sample,NaN,NaN,NaN
1,2,TARGET,Target variable (1 - client with payment diffi...,NaN,NaN,NaN
3,5,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN,NaN,NaN
3,6,CODE_GENDER,Gender of the client,NaN,NaN,NaN
4,7,FLAG_OWN_CAR,Flag if the client owns a car,NaN,NaN,NaN
5,8,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN,NaN,NaN
6,9,CNT_CHILDREN,Number of children the client has,NaN,NaN,NaN
7,10,AMT_INCOME_TOTAL,Income of the client,NaN,NaN,NaN
8,11,AMT_CREDIT,Credit amount of the loan,NaN,NaN,NaN
9,12,AMT_ANNUITY,Loan annuity,NaN,NaN,NaN
10,13,AMT_GOODS_PRICE,For consumer loans it is the price of the good...,NaN,NaN,NaN
11,14,NAME_TYPE_SUITE,Who was accompanying client when he was applyi...,NaN,NaN,NaN
12,15,NAME_INCOME_TYPE,"Clients income type (businessman, working, mat...",NaN,NaN,NaN
13,16,NAME_EDUCATION_TYPE,Level of highest education the client achieved,NaN,NaN,NaN
14,17,NAME_FAMILY_STATUS,Family status of the client,NaN,NaN,NaN
15,18,NAME_HOUSING_TYPE,What is the housing situation of the client (r...,NaN,NaN,NaN
16,19,REGION_POPULATION_RELATIVE,Normalized population of region where client l...,normalized,NaN,NaN
17,20,DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application,NaN,NaN
18,21,DAYS_EMPLOYED,How many days before the application the perso...,time only relative to the application,NaN,NaN
19,22,DAYS_REGISTRATION,How many days before the application did clien...,time only relative to the application,NaN,NaN
20,23,DAYS_ID_PUBLISH,How many days before the application did clien...,time only relative to the application,NaN,NaN
21,24,OWN_CAR_AGE,Age of client's car,NaN,NaN,NaN
22,25,FLAG_MOBIL,"Did client provide mobile phone (1=YES, 0=NO)",NaN,NaN,NaN
23,26,FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)",NaN,NaN,NaN
24,27,FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN,NaN,NaN
25,28,FLAG_CONT_MOBILE,"Was mobile phone reachable (1=YES, 0=NO)",NaN,NaN,NaN
26,29,FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)",NaN,NaN,NaN
27,30,FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)",NaN,NaN,NaN
28,31,OCCUPATION_TYPE,What kind of occupation does the client have,NaN,NaN,NaN
29,32,CNT_FAM_MEMBERS,How many family members does client have,NaN,NaN,NaN
...,...,...,...,...,...,...
175,178,NAME_CONTRACT_TYPE,"Contract product type (Cash loan, consumer loa...",NaN,NaN,NaN
176,179,AMT_ANNUITY,Annuity of previous application,NaN,NaN,NaN
177,180,AMT_APPLICATION,For how much credit did client ask on the prev...,NaN,NaN,NaN
178,181,AMT_CREDIT,Final credit amount on the previous applicatio...,NaN,NaN,NaN
179,182,AMT_DOWN_PAYMENT,Down payment on the previous application,NaN,NaN,NaN
180,183,AMT_GOODS_PRICE,Goods price of good that client asked for (if ...,NaN,NaN,NaN
181,184,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...,NaN,NaN,NaN
182,185,HOUR_APPR_PROCESS_START,Approximately at what day hour did the client ...,rounded,NaN,NaN
183,186,FLAG_LAST_APPL_PER_CONTRACT,Flag if it was last application for the previo...,NaN,NaN,NaN
184,187,NFLAG_LAST_APPL_IN_DAY,Flag if the application was the last applicati...,NaN,NaN,NaN
185,188,NFLAG_MICRO_CASH,Flag Micro finance loan,NaN,NaN,NaN
186,189,RATE_DOWN_PAYMENT,Down payment rate normalized on previous credit,normalized,NaN,NaN
187,190,RATE_INTEREST_PRIMARY,Interest rate normalized on previous credit,normalized,NaN,NaN
188,191,RATE_INTEREST_PRIVILEGED,Interest rate normalized on previous credit,normalized,NaN,NaN
189,192,NAME_CASH_LOAN_PURPOSE,Purpose of the cash loan,NaN,NaN,NaN
190,193,NAME_CONTRACT_STATUS,"Contract status (approved, cancelled, ...) of ...",NaN,NaN,NaN
191,194,DAYS_DECISION,Relative to current application when was the d...,time only relative to the application,NaN,NaN
192,195,NAME_PAYMENT_TYPE,Payment method that client chose to pay for th...,NaN,NaN,NaN
193,196,CODE_REJECT_REASON,Why was the previous application rejected,NaN,NaN,NaN
194,197,NAME_TYPE_SUITE,Who accompanied client when applying for the p...,NaN,NaN,NaN
195,198,NAME_CLIENT_TYPE,Was the client old or new client when applying...,NaN,NaN,NaN
196,199,NAME_GOODS_CATEGORY,What kind of goods did the client apply for in...,NaN,NaN,NaN
197,200,NAME_PORTFOLIO,"Was the previous application for CASH, POS, CA...",1,"2 or more previous loans in Home Credit)""",hashed
198,215,SK_ID_CURR,ID of loan in our sample,hashed,NaN,NaN
199,216,NUM_INSTALMENT_VERSION,Version of installment calendar (0 is for cred...,NaN,NaN,NaN
200,217,NUM_INSTALMENT_NUMBER,On which installment we observe payment,NaN,NaN,NaN
201,218,DAYS_INSTALMENT,When the installment of previous credit was su...,time only relative to the application,NaN,NaN
202,219,DAYS_ENTRY_PAYMENT,When was the installments of previous credit p...,time only relative to the application,NaN,NaN
203,220,AMT_INSTALMENT,What was the prescribed installment amount of ...,NaN,NaN,NaN
204,221,AMT_PAYMENT,What the client actually paid on previous cred...,NaN,NaN,NaN